// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU9pCb9HNSTBstuDoFj7HMm0yS8yoL92k',
    appId: '1:468699766386:web:83c403145a13d59aa92ceb',
    messagingSenderId: '468699766386',
    projectId: 'novabot-bb073',
    authDomain: 'novabot-bb073.firebaseapp.com',
    storageBucket: 'novabot-bb073.appspot.com',
    measurementId: 'G-QCETJKKBG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1RP-ex5nGYWliBqZ-_wh24a-ym3d5-3I',
    appId: '1:468699766386:android:ab8575ef85299ecca92ceb',
    messagingSenderId: '468699766386',
    projectId: 'novabot-bb073',
    storageBucket: 'novabot-bb073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKN6_T45cLuETknxgkOihOZuD-nV6bAIo',
    appId: '1:468699766386:ios:bffc8caada90e24fa92ceb',
    messagingSenderId: '468699766386',
    projectId: 'novabot-bb073',
    storageBucket: 'novabot-bb073.appspot.com',
    iosClientId: '468699766386-gdueaqfqare54q75ot0s5lujtqnas0pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiChatAppTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKN6_T45cLuETknxgkOihOZuD-nV6bAIo',
    appId: '1:468699766386:ios:bffc8caada90e24fa92ceb',
    messagingSenderId: '468699766386',
    projectId: 'novabot-bb073',
    storageBucket: 'novabot-bb073.appspot.com',
    iosClientId: '468699766386-gdueaqfqare54q75ot0s5lujtqnas0pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.geminiChatAppTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU9pCb9HNSTBstuDoFj7HMm0yS8yoL92k',
    appId: '1:468699766386:web:b83ff350189833dca92ceb',
    messagingSenderId: '468699766386',
    projectId: 'novabot-bb073',
    authDomain: 'novabot-bb073.firebaseapp.com',
    storageBucket: 'novabot-bb073.appspot.com',
    measurementId: 'G-PKQZDHJPJD',
  );
}
